services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
    networks:
      - tp3net

  script:
    build: ./script
    image: php-mysqli
    container_name: script
    volumes:
      - ./app:/app
    depends_on:
      - data
    networks:
      - tp3net

  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - script
    networks:
      - tp3net

networks:
  tp3network:
    driver: bridge
